channels:
  - conda-forge
  - defaults

dependencies:
  - openmdao==3.36.0
  - moorpy==1.1.0
  - dash
  - dill
  - jsonmerge
  - mat4py
  - nlopt
  - numpydoc
  - openfast==4.0.2
  - openraft==1.3.2
  - osqp  
  - pcrunch<=1.9
  - pip
  - pyhams==1.3.0
  #- pyoptsparse
  - rosco==2.9.7
  - smt
  - wisdem==3.19.0
  - pip:
    - dash-bootstrap-components
    - dash-mantine-components
    - dash-vtk
    - pyvista
    - dearpygui
    - openfast_io==4.0.2
    - marmot-agents
# Needs to be done outside of environment file:
#  - m2w64-toolchain # [win]
#  - libpython # [win]
#  - compilers # [not win]
#  - petsc4py # [not win]
#  - mpi4py # [not win]
